DROP TABLE IF EXISTS `__PREFIX__addons_changyan_site`;
CREATE TABLE `__PREFIX__addons_changyan_site` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `appId` varchar(100) DEFAULT NULL COMMENT 'appId',
  `appKey` varchar(150) DEFAULT NULL COMMENT 'appKey',
  `conf` varchar(100) DEFAULT NULL COMMENT 'conf',
  `auditMode` int(10) unsigned DEFAULT '0' COMMENT 'auditMode',
  `exchange` int(10) unsigned DEFAULT '0' COMMENT 'exchange',
  `exchangeAuditType` int(10) DEFAULT '0' COMMENT 'exchangeAuditType',
  `exchangeLimit` int(10) DEFAULT '0' COMMENT 'exchangeLimit',
  `filter` int(10) DEFAULT '0' COMMENT 'filter',
  `isvAuditType` tinyint(4) DEFAULT '0' COMMENT 'isvAuditType',
  `isvType` varchar(50) DEFAULT NULL COMMENT '站点类型',
  `name` varchar(50) DEFAULT NULL COMMENT '站点名称',
  `officialUserId` varchar(50) DEFAULT NULL COMMENT '公共用户ID',
  `qualityExchange` varchar(50) DEFAULT NULL COMMENT 'qualityExchange',
  `sso` varchar(50) DEFAULT NULL COMMENT 'sso',
  `status` tinyint(4) DEFAULT '0' COMMENT '状态',
  `sysAudit` varchar(50) DEFAULT NULL COMMENT 'sysAudit',
  `url` varchar(255) DEFAULT NULL COMMENT 'url',
  `vip` varchar(255) DEFAULT NULL COMMENT 'vip',
  `create_time` int(11) DEFAULT '0' COMMENT '添加时间',
  `update_time` int(11) unsigned DEFAULT '0' COMMENT '更新时间',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `appId` (`appId`),
  KEY `create_time` (`create_time`),
  KEY `name` (`name`),
  KEY `officialUserId` (`officialUserId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='站点表';

DROP TABLE IF EXISTS `__PREFIX__addons_changyan_comments`;
CREATE TABLE `__PREFIX__addons_changyan_comments` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `siteid` int(10) DEFAULT '0' COMMENT '站点ID',
  `replyid` bigint(20) unsigned DEFAULT '0' COMMENT '回复ID',
  `referid` bigint(20) DEFAULT '0' COMMENT 'referid',
  `thirdid` int(10) unsigned DEFAULT '0' COMMENT '三方ID',
  `sourceid` varchar(50) DEFAULT NULL COMMENT '原始ID',
  `bookid` int(10) unsigned DEFAULT '0' COMMENT '作品ID',
  `booktitle` varchar(100) DEFAULT NULL COMMENT '作品标题',
  `chapterid` int(10) unsigned DEFAULT '0' COMMENT '章节ID',
  `chaptertitle` varchar(100) DEFAULT NULL COMMENT '章节标题',
  `userid` bigint(20) DEFAULT '0' COMMENT '用户ID',
  `nickname` varchar(255) DEFAULT NULL COMMENT '用户昵称',
  `headimg` varchar(255) DEFAULT NULL COMMENT '头像',
  `content` text COMMENT '评论内容',
  `attachs` text COMMENT '图片评论',
  `likenum` int(10) unsigned DEFAULT '0' COMMENT '喜欢数',
  `sharenum` int(10) unsigned DEFAULT '0' COMMENT '分享数',
  `spnum` int(10) unsigned DEFAULT '0' COMMENT '顶次数',
  `opnum` int(10) unsigned DEFAULT '0' COMMENT '踩次数',
  `from` varchar(50) DEFAULT NULL COMMENT '用户账号来源',
  `status` tinyint(4) DEFAULT '0' COMMENT '状态',
  `channeltype` tinyint(4) DEFAULT '0' COMMENT '评论类型',
  `ip` varchar(50) DEFAULT NULL COMMENT 'IP',
  `create_time` int(11) DEFAULT '0' COMMENT '添加时间',
  `update_time` int(11) unsigned DEFAULT '0' COMMENT '更新时间',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `thirdid` (`thirdid`),
  KEY `replyid` (`replyid`) USING BTREE,
  KEY `bookid` (`bookid`) USING BTREE,
  KEY `chapterid` (`chapterid`) USING BTREE,
  KEY `create_time` (`create_time`),
  KEY `update_time` (`update_time`),
  KEY `sourceid` (`sourceid`),
  KEY `userid` (`userid`),
  KEY `siteid` (`siteid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='评论表';

DROP TABLE IF EXISTS `__PREFIX__addons_changyan_topic`;
CREATE TABLE `__PREFIX__addons_changyan_topic` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `siteid` int(10) DEFAULT '0' COMMENT '站点ID',
  `topic_source_id` varchar(100) DEFAULT NULL COMMENT 'sourceid',
  `bookid` int(10) DEFAULT '0' COMMENT '作品ID',
  `booktitle` varchar(200) DEFAULT NULL COMMENT '作品名称',
  `chapterid` int(10) DEFAULT '0' COMMENT '章节ID',
  `chaptertitle` varchar(200) DEFAULT NULL COMMENT '章节名称',
  `topic_url` varchar(255) DEFAULT NULL COMMENT 'topic_url',
  `create_time` int(11) DEFAULT '0' COMMENT '添加时间',
  `update_time` int(11) unsigned DEFAULT '0' COMMENT '更新时间',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `create_time` (`create_time`),
  KEY `topic_source_id` (`topic_source_id`) USING BTREE,
  KEY `topic_url` (`topic_url`),
  KEY `siteid` (`siteid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='主题表';